// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopHub.API.Data;

#nullable disable

namespace ShopHub.API.Migrations
{
    [DbContext(typeof(ShopHubDbContext))]
    [Migration("20260817185542_OverSizedTeesAdd")]
    partial class OverSizedTeesAdd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShopHub.API.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fashion"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Shoes"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Accessories"
                        });
                });

            modelBuilder.Entity("ShopHub.API.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ShopHub.API.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("ShopHub.API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Rating")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Latest Apple smartphone with powerful performance.",
                            Image = "https://images.unsplash.com/photo-1592899677977-9c10ca588bbd",
                            Name = "iPhone 15",
                            Price = 199999m,
                            Rating = 4.8m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Lightweight laptop with excellent performance.",
                            Image = "https://images.unsplash.com/photo-1517336714731-489689fd1ca8",
                            Name = "MacBook Air",
                            Price = 289999m,
                            Rating = 4.9m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Premium wireless headphones with clear sound.",
                            Image = "https://images.unsplash.com/photo-1505740420928-5e560c06d30e",
                            Name = "Sony Headphones",
                            Price = 45999m,
                            Rating = 4.7m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Comfortable premium cotton hoodie.",
                            Image = "https://images.unsplash.com/photo-1556821840-3a63f95609a7",
                            Name = "Classic Hoodie",
                            Price = 5999m,
                            Rating = 4.5m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Classic denim jacket for everyday style.",
                            Image = "https://images.unsplash.com/photo-1551028719-00167b16eac5",
                            Name = "Denim Jacket",
                            Price = 7999m,
                            Rating = 4.6m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Description = "Comfortable sneakers designed for everyday use.",
                            Image = "https://images.unsplash.com/photo-1542291026-7eec264c27ff",
                            Name = "Nike Air Max",
                            Price = 24999m,
                            Rating = 4.8m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            Description = "Premium genuine leather wallet.",
                            Image = "https://images.unsplash.com/photo-1627123424574-724758594e93",
                            Name = "Leather Wallet",
                            Price = 3499m,
                            Rating = 4.4m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Description = "Elegant watch suitable for casual and formal wear.",
                            Image = "https://images.unsplash.com/photo-1524805444758-089113d48a6d",
                            Name = "Classic Watch",
                            Price = 12999m,
                            Rating = 4.7m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Description = "Stylish relaxed fit baggy jeans for a comfortable and modern look.",
                            Image = "https://images.unsplash.com/photo-1674075872359-a174bc7ed420?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8QmFnZ3klMjBqZWFuc3xlbnwwfHwwfHx8MA%3D%3D",
                            Name = "Baggy Jeans",
                            Price = 4999m,
                            Rating = 4.5m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Description = "Stylish relaxed fit baggy jeans for a comfortable and modern look.",
                            Image = " https://plus.unsplash.com/premium_photo-1673356301535-2cc45bcc79e4?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTN8fE92ZXIlMjBzaXplZCUyMHRlZXN8ZW58MHx8MHx8fDA%3D\r\n",
                            Name = "Baggy Jeans",
                            Price = 4999m,
                            Rating = 4.5m
                        });
                });

            modelBuilder.Entity("ShopHub.API.Models.OrderItem", b =>
                {
                    b.HasOne("ShopHub.API.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShopHub.API.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ShopHub.API.Models.Product", b =>
                {
                    b.HasOne("ShopHub.API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ShopHub.API.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ShopHub.API.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("ShopHub.API.Models.Product", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
